### ISSUE TITLE
Device selection does not display the options

### ISSUE THREAD

**Issue by a-cute-accent** [imgrant/openmediavault-luksencryption#1]
When trying to create an encrypted device, no device can be selected from the roll-down menu because none is displayed. 

There are a  a number of physical devices mounted on the system.

openmediavault                  3.0.70
openmediavault-luksencryption 3.0.2
firefox 53.0 (64-bit)
chromium Version 58.0.3029.81 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

![openmediavault control panel shuttle local](https://cloud.githubusercontent.com/assets/28449397/25771893/eacf557c-325d-11e7-8a48-820652d8cced.png)

**Comment by imgrant** [comment]
This repository is no longer maintained, development switched to [https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption) some time ago, please raise your issue there.
