### ISSUE TITLE
OMV luks encryption plugin corrupts OMV database

### ISSUE THREAD

**Issue by petaramesh** [imgrant/openmediavault-luksencryption#2]
![omv_notif_errors](https://user-images.githubusercontent.com/6459325/32405537-cc61fa56-c167-11e7-9049-5052c1174035.png)

Hello,

When entering OMV's « Notication » tab, I now get this error (pls see attached image) that prevents me from using it. As it talks about "luks", I assume this has someting to do with the luks encryption plugin having modified OMV's database in a way that conflicts with the « notifications » tab.

Any clue about how to fix this ?

Thanks is advance?

**Comment by imgrant** [comment]
Hi,

This repo is effectively closed now, development has moved to: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption
